class AppStrings {
  static const String noRouteFound = "No Route Found";
  static const String timeoutError = "Request Timeout";
  static const String requestCanceled = "Request Canceled";
  static const String unKnownError = "UnKnown Error";
  static const String cacheError = "Cache Error";
  static const String noInternetError = "No Internet Connection";
  static const String badCertificate = "Bad Certificate";
  static const String connectionError = "connection Error";
  static const String loading = "Loading...";
  static const String ok = "OK";
  static const String retryAgain = "Retry Again";
  static const String success = "Success";
  static const String name = "Name";
  static const String nameHintText = "Enter your name";
  static const String nameErrorText = "Enter your name";
  static const String email = "E-mail";
  static const String emailHintText = "Enter your email";
  static const String emailErrorText = "E-mail is too short";
  static const String password = "Password";
  static const String passwordHintText = "Enter your password";
  static const String passwordErrorText = "Password is too short";
  static const String phone = "Phone";
  static const String phoneHintText = "Enter your phone";
  static const String phoneErrorText = "Enter your phone";
  static const String forgetPassword = "Forgot your password?";
  static const String dontHaveAccount  = "Don't have an account? ";
  static const String create  = 'Create';
}